version: '3.9'

services:
  
  backend:
    container_name: fitness-gpt-backend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - ./.env
    networks:
      - fitness-gpt-network

  postgres:
    container_name: fitness-gpt-postgres
    image: postgres:14-alpine
    ports:
      - 5432:5432
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres_db
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U username -d postgres_db" ]
      interval: 3s
      timeout: 5s
      retries: 4
      start_period: 3s
    networks:
      - fitness-gpt-network

volumes:
  db:

networks:
  fitness-gpt-network: